### ISSUE TITLE
Licensing issues.

### ISSUE THREAD

**Issue by amoooooo** [darknessNBK/minevisionai#1]
If ANY of the art this is trained on is ARR this entire project is entirely breaking copyright laws. Seeing so much origin realms inspiration makes me think there's been zero license research done into this, and i sure as hell bet mods with separate licenses for assets and code weren't checked either.

**Comment by darknessNBK** [comment]
Our datasets are copyright free. Thanks for the concern.

**Comment by amoooooo** [comment]
Other than the origin realms portraits which are ARR as the original creator of the style and the one who did the art for OR saying they cannot be used?

**Comment by darknessNBK** [comment]
Thank you for your continued interest in this matter. We respect the importance of intellectual property rights and have taken considerable efforts to ensure compliance with all relevant laws and regulations. 

The portraits used to train our AI, as I previously mentioned, were specifically created for this purpose by our in-house artist, Bread09. These were original pieces of work, and their creation and use adhere to all relevant copyright laws.

While there's a similarity in style to Origin Realms, it's important to remember that copyright law doesn't protect styles or techniques - it protects the specific expression of an idea. Just like an artist might paint in the style of Van Gogh or Monet without infringing on copyright, creating Minecraft portraits in a similar style to those seen in Origin Realms does not constitute infringement.

Furthermore, the AI we've developed isn't copying or reproducing specific pieces of copyrighted work - it's creating new, original works based on the dataset we've fed into it. This is a crucial distinction under copyright law.

Lastly, Ben, the Managing Director of Origin Realms, who was among the first invited to review our project. He had the opportunity to raise any potential concerns, and to the best of our knowledge, there weren't any.

We appreciate your vigilance in upholding the standards of the creative community. We assure you that we're equally committed to these principles and strive to respect the rights of all creators. We are confident that our operation abides by the letter and spirit of intellectual property laws.
